dist: trusty
language: go

go:
  - "1.10.2"

go_import_path: wio

before_install:
  - source wenv
  - sudo apt-get update
  - sudo apt-get install gcc-avr avr-libc avrdude

install:
  - wmake travis-setup

script:
  - wmake build
  - go test -v ./...
  - cd test
  - ./runtests.sh
